language: cpp
dist: zesty
addons:
  apt:
    packages:
      - libsfml-dev
      - cmake
script:
  - gcc --version
  - g++ --version
  - cmake --version
  - cmake . -G "Unix Makefiles"
  - make
  - cat /home/travis/build/Zac-Garby/solar-system/CMakeFiles/CMakeOutput.log
